name: Build Android APK
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install npm packages
        run: npm install

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK File
        uses: actions/upload-artifact@v4
        with:
          name: FTP-Pro-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
